sudo: false

os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.19 TARGET_NODE_VERSION=node

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION
  - npm install -g elm-test@0.19.0-rev4

script:
  - elm make && elm-test
